# Generated by Django 4.2.27 on 2026-02-01 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年齢')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='身長(cm)')),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', 'その他'), ('N', '未回答')], default='N', max_length=1, verbose_name='性別')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
