# Generated by Django 4.2.27 on 2026-02-01 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='menus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calories', models.IntegerField(default=0, verbose_name='カロリー(kcal)')),
                ('protein', models.FloatField(default=0, verbose_name='たんぱく質(g)')),
                ('fat', models.FloatField(default=0, verbose_name='脂質(g)')),
                ('carbs', models.FloatField(default=0, verbose_name='炭水化物(g)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
