# Generated by Django 4.2.27 on 2026-01-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='料理名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('calories', models.IntegerField(verbose_name='カロリー(kcal)')),
                ('protein', models.FloatField(default=0, verbose_name='タンパク質(g)')),
                ('fat', models.FloatField(default=0, verbose_name='脂質(g)')),
                ('carbs', models.FloatField(default=0, verbose_name='炭水化物(g)')),
                ('category', models.CharField(choices=[('morning', '朝食'), ('lunch', '昼食'), ('dinner', '夕食')], default='dinner', max_length=20, verbose_name='カテゴリ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='料理写真')),
            ],
        ),
    ]
