# Generated by Django 4.2.27 on 2026-01-31 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_activity_score', models.IntegerField(choices=[(20, '座りっぱなし (20点)'), (40, 'たまに歩く (40点)'), (90, 'よく体を動かす (90点)')], default=20, verbose_name='普段の運動')),
                ('is_smoker', models.BooleanField(default=False, verbose_name='喫煙習慣 (-20点)')),
                ('drinks_daily', models.BooleanField(default=False, verbose_name='毎日の飲酒 (-20点)')),
                ('low_water', models.BooleanField(default=False, verbose_name='水分不足 (-10点)')),
                ('high_stress', models.BooleanField(default=False, verbose_name='ストレスが高い (-10点)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='記録日')),
                ('movement_diff', models.IntegerField(choices=[(10, 'いつもより動いた (+10)'), (0, 'いつも通り (0)'), (-10, '動かなかった (-10)')], default=0, verbose_name='今日の運動量')),
                ('meals_count', models.IntegerField(default=0, help_text='0~3回', verbose_name='食事記録回数')),
                ('protein_ok', models.BooleanField(default=False, verbose_name='タンパク質80%以上')),
                ('fat_ok', models.BooleanField(default=False, verbose_name='脂質適正')),
                ('veggies_ok', models.BooleanField(default=False, verbose_name='野菜適正')),
                ('late_night_meal', models.BooleanField(default=False, verbose_name='22時以降の食事 (-10)')),
                ('skip_breakfast', models.BooleanField(default=False, verbose_name='朝食抜き (-10)')),
                ('good_balance', models.BooleanField(default=False, verbose_name='3食バランス良好 (+20)')),
                ('sleep_quality_good', models.BooleanField(default=False, verbose_name='睡眠の質が良い')),
                ('mental_good', models.BooleanField(default=False, verbose_name='メンタル良好')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
