# Generated by Django 4.2.27 on 2026-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthprofile_dailyhealthlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyhealthlog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='target_score',
            field=models.IntegerField(default=80, verbose_name='目標スコア'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='base_activity_score',
            field=models.IntegerField(choices=[(20, 'Lv1: ほぼ座りっぱなし (20点)'), (40, 'Lv2: 通勤・通学程度 (40点)'), (60, 'Lv3: 軽い運動習慣あり (60点)'), (80, 'Lv4: 運動習慣あり (80点)'), (100, 'Lv5: ジム等で体を動かす (100点)')], default=40, verbose_name='普段の運動'),
        ),
    ]
