# Generated by Django 4.2.27 on 2026-02-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dailyhealthlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='例：豚肉 100g（改行して入力）', verbose_name='材料・分量'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, help_text='例：1. 野菜を切る（改行して入力）', verbose_name='作り方手順'),
        ),
    ]
