# Generated by Django 4.2.27 on 2026-02-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_ingredients_recipe_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='料理の紹介文'),
        ),
    ]
